import axios from 'axios';
import { PokemonFormData } from '../types/pokemon';

const POLLINATIONS_API_URL = 'https://image.pollinations.ai/prompt/';

export async function generatePokemonImage(data: PokemonFormData): Promise<string> {
  const prompt = generatePrompt(data);
  const encodedPrompt = encodeURIComponent(prompt);
  const imageUrl = `${POLLINATIONS_API_URL}${encodedPrompt}`;
  
  // Verify the image is generated by making a HEAD request
  await axios.head(imageUrl);
  
  return imageUrl;
}

function generatePrompt(data: PokemonFormData): string {
  const basePrompt = `a detailed illustration of a ${data.style} Pokemon creature of the ${data.type} type named ${data.name}`;
  
  const styleModifiers = {
    cute: 'adorable, kawaii style, soft colors',
    fierce: 'powerful, dynamic pose, intense colors',
    mystical: 'ethereal, magical aura, mysterious',
    robotic: 'mechanical parts, metallic texture, sci-fi',
    elemental: 'natural elements, organic design',
    ancient: 'ancient symbols, weathered appearance, mythological'
  };

  const typeModifiers = {
    fire: 'flames, warm colors, heat waves',
    water: 'aquatic features, flowing design, bubbles',
    electric: 'lightning patterns, sparks, energy',
    grass: 'plant elements, leaves, natural',
    psychic: 'cosmic energy, psychedelic patterns',
    dragon: 'scales, majestic presence, mythical',
    ghost: 'ethereal, transparent parts, spooky',
    fairy: 'sparkles, pastel colors, whimsical',
    dark: 'shadows, dark aura, mysterious',
    steel: 'metallic surface, mechanical parts',
    ice: 'crystalline structure, frost patterns',
    ground: 'earthy textures, robust design',
    rock: 'mineral patterns, crystalline features',
    fighting: 'muscular build, dynamic pose',
    poison: 'toxic colors, chemical elements',
    bug: 'insect features, compound eyes',
    flying: 'aerodynamic design, wings',
    normal: 'balanced design, natural features'
  };

  const style = styleModifiers[data.style as keyof typeof styleModifiers] || '';
  const type = typeModifiers[data.type as keyof typeof typeModifiers] || '';

  return `${basePrompt}, ${style}, ${type}, digital art, high quality, detailed, Pokemon style, game art`;
}